In [1]:
if 'google.colab' in str(get_ipython()):
    from google.colab import userdata
    access_token = userdata.get('DEFORMER_TOKEN')
    !pip install git+https://$access_token@github.com/ay94/deformer-extractor.git@error-handling

In [11]:
from experiment_utils import colab
from experiment_utils.general_utils import FileHandler
from tqdm.autonotebook import tqdm

In [3]:
base_folder = colab.init('My Drive')
config_path = base_folder / 'Final Year Experiments/Class Imbalance/1_fineTuning'
fh = FileHandler(config_path)

2024-07-20 21:49:37 - WARNING - Resolved path does not exist, checking alternative paths: /Users/ay227/Desktop/Final-Year/Thesis-Experiments/Data-Extraction-Phase/notebooks/My Drive
2024-07-20 21:49:37 - INFO - Found Google Drive directory for account ahmed.younes.sam@gmail.com: /Users/ay227/Library/CloudStorage/GoogleDrive-ahmed.younes.sam@gmail.com


In [4]:
model_name='arabertv02'
data_name='ANERCorp_CamelLab'

In [5]:
import torch
training_outputs = fh.load_pickle(
            f"evalOutputs/{model_name}_{data_name}_regular_outputs.pkl"
        )
load_model_path = fh.file_path / f"trainOutputs/{model_name}_{data_name}_regular.bin"
model = torch.load(load_model_path, map_location=torch.device('cpu'))
        

In [6]:
training_outputs.test_dataloader.dataset[0]['inpy']

tensor([-100,    5,    5,    0,    1,    2, -100, -100,    0,    0,    0,    0,
           1,    2,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0, -100,    0,    0,    0,    0,    0,    0,    0,    5,    5, -100,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -1

In [7]:
from experiment_utils.model_outputs_utils import BatchOutputs, ModelOutputs, ModelResults, GenerateSplitBatches

In [8]:
outputs = GenerateSplitBatches(training_outputs, model, training_outputs.test_dataloader)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


  0%|          | 0/121 [00:00<?, ?it/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Compute Outputs


In [25]:
outputs.outputs.aligned_losses[0][:49]

tensor([0.0000e+00, 3.0585e-01, 2.1982e-02, 1.0366e-03, 2.2747e-02, 1.3149e-02,
        0.0000e+00, 0.0000e+00, 5.3392e-04, 4.0292e-05, 1.0251e-04, 1.8690e-04,
        2.0437e-03, 4.0239e-03, 4.9590e-05, 3.5405e-05, 3.8981e-05, 2.7299e-05,
        3.9934e-05, 3.8742e-05, 6.1868e-05, 5.4358e-05, 3.1590e-05, 3.4809e-05,
        8.4277e-05, 0.0000e+00, 6.2702e-05, 3.4570e-05, 4.5060e-05, 6.2941e-05,
        5.5192e-05, 3.3616e-05, 5.4142e-04, 1.5900e-02, 2.2703e-01, 0.0000e+00,
        5.4716e-05, 1.3267e-01, 8.1702e-03, 3.2782e-05, 3.7073e-05, 3.8265e-05,
        3.6001e-05, 2.6106e-05, 1.6783e-04, 7.0212e-05, 6.6397e-05, 4.4822e-05,
        0.0000e+00])

In [30]:
for k, v in outputs.batches[0].items():
    print(k, type(v))

labels <class 'torch.Tensor'>
words_ids <class 'torch.Tensor'>
sentence_num <class 'torch.Tensor'>
attention_mask <class 'torch.Tensor'>
input_ids <class 'torch.Tensor'>
losses <class 'torch.Tensor'>
logits <class 'torch.Tensor'>
last_hidden_state <class 'torch.Tensor'>


In [17]:
outputs.batches[0]['losses'][:49]

tensor([0.0000e+00, 3.0585e-01, 2.1982e-02, 1.0366e-03, 2.2747e-02, 1.3149e-02,
        0.0000e+00, 0.0000e+00, 5.3392e-04, 4.0292e-05, 1.0251e-04, 1.8690e-04,
        2.0437e-03, 4.0239e-03, 4.9590e-05, 3.5405e-05, 3.8981e-05, 2.7299e-05,
        3.9934e-05, 3.8742e-05, 6.1868e-05, 5.4358e-05, 3.1590e-05, 3.4809e-05,
        8.4277e-05, 0.0000e+00, 6.2702e-05, 3.4570e-05, 4.5060e-05, 6.2941e-05,
        5.5192e-05, 3.3616e-05, 5.4142e-04, 1.5900e-02, 2.2703e-01, 0.0000e+00,
        5.4716e-05, 1.3267e-01, 8.1702e-03, 3.2782e-05, 3.7073e-05, 3.8265e-05,
        3.6001e-05, 2.6106e-05, 1.6783e-04, 7.0212e-05, 6.6397e-05, 4.4822e-05,
        0.0000e+00])

In [28]:
outputs.batches[0]['input_ids']

tensor([[    2, 40508, 32479,  ...,     0,     0,     0],
        [    2, 13654,   196,  ...,     0,     0,     0],
        [    2, 20029, 59364,  ...,     0,     0,     0],
        ...,
        [    2,  9349,  7377,  ...,     0,     0,     0],
        [    2,  2382,  7914,  ...,     0,     0,     0],
        [    2,  1297,   418,  ...,     0,     0,     0]])

In [43]:
outputs.batches[0]['logits'][0][:49]

tensor([[ 1.0477e+01, -1.1675e+00, -1.4375e+00, -3.5794e-01, -1.8591e+00,
          3.9068e-01, -2.2532e+00,  3.3258e-01, -1.3825e+00],
        [ 3.9684e+00, -4.9718e-01, -2.9311e+00,  1.3824e+00, -1.6737e+00,
          5.0959e+00, -1.3564e+00, -8.6886e-01, -3.3768e+00],
        [ 1.1132e+00, -1.1276e+00, -2.5151e+00,  9.1764e-01, -1.1936e+00,
          6.1062e+00,  1.2681e+00, -2.5758e+00, -2.4657e+00],
        [ 8.0553e+00, -1.2848e+00, -1.9229e+00, -1.1450e+00, -3.6577e-01,
          1.1940e-02, -1.7050e+00, -9.2705e-01, -1.4149e+00],
        [ 1.8336e+00,  5.9974e+00,  2.0844e-01, -4.6786e-01, -1.0844e+00,
         -1.5087e+00, -1.9922e+00, -1.0235e+00, -2.4271e+00],
        [ 4.8394e-01,  1.0256e+00,  6.3280e+00, -2.3858e+00,  6.3513e-01,
         -1.1173e+00, -1.3946e+00, -1.7036e+00, -1.3290e+00],
        [ 9.7876e-01,  7.9919e-01,  5.5206e+00, -2.7252e+00,  5.1916e-01,
         -9.8715e-01, -1.1156e+00, -1.5150e+00, -1.0666e+00],
        [ 1.5994e+00,  3.2888e-01,  3.9372e+00, 

In [29]:
outputs.batches[0]['input_ids']

torch.Size([8, 256])

In [12]:
from dataclasses import dataclass, field
import torch
from typing import List
from tqdm.autonotebook import tqdm

@dataclass
class SentenceData:
    input_ids: torch.Tensor
    attention_mask: torch.Tensor
    last_hidden_states: torch.Tensor
    losses: torch.Tensor
    logits: torch.Tensor
    labels: torch.Tensor
    


@dataclass
class BatchData:
    input_ids: torch.Tensor
    attention_mask: torch.Tensor
    last_hidden_states: torch.Tensor
    losses: torch.Tensor
    logits: torch.Tensor
    labels: torch.Tensor

    def detach(self):
        """Detach all tensors to move them to CPU and reduce memory footprint on GPU."""
        for attr, value in self.__dict__.items():
            if isinstance(value, torch.Tensor):
                setattr(self, attr, value.detach().cpu())
            elif isinstance(value, tuple) and all(torch.is_tensor(x) for x in value):
                # If the batch is a tuple of tensors (like hidden states), process each tensor.
                detached_batch = tuple(layer.detach().cpu() for layer in value)
                setattr(self, attr, detached_batch)
            else:
                raise TypeError("Unsupported batch type: {}".format(type(value)))




In [13]:
def process_model_output(data_loader, model, device):
    model.eval()
    processed_batches = []
    with torch.no_grad():
        for data in tqdm(data_loader):
            data = {k: v.to(device) for k, v in data.items()}
            outputs = model(**data)
            batch = BatchData(
                input_ids=data['input_ids'],
                attention_mask=data['attention_mask'],
                last_hidden_states=outputs['last_hidden_state'],
                losses=outputs['losses'],
                logits=outputs['logits'],
                labels=data['labels'],
            )
            batch.detach()
            processed_batches.append(batch)
    return processed_batches


In [14]:
data_loader = training_outputs.test_dataloader
device = torch.device('cpu')
processed_batches = process_model_output(data_loader, model, device)


  0%|          | 0/121 [00:00<?, ?it/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [19]:
batch = processed_batches[0]

In [20]:
from collections import Counter
for idx in range(batch.input_ids.size(0)):  # Iterate over each sentence in the batch
        sentence_mask = batch.input_ids[idx] != 0
        print(Counter(sentence_mask.tolist()))

Counter({False: 207, True: 49})
Counter({False: 220, True: 36})
Counter({False: 236, True: 20})
Counter({False: 232, True: 24})
Counter({False: 225, True: 31})
Counter({False: 222, True: 34})
Counter({False: 186, True: 70})
Counter({False: 218, True: 38})


In [21]:
49+36+20+24+31+34+70+38

302

In [25]:
processed_batches[0]

BatchData(input_ids=tensor([[    2, 40508, 32479,  ...,     0,     0,     0],
        [    2, 13654,   196,  ...,     0,     0,     0],
        [    2, 20029, 59364,  ...,     0,     0,     0],
        ...,
        [    2,  9349,  7377,  ...,     0,     0,     0],
        [    2,  2382,  7914,  ...,     0,     0,     0],
        [    2,  1297,   418,  ...,     0,     0,     0]]), attention_mask=tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), last_hidden_states=tensor([[[ 0.4485,  0.0872, -1.0895,  ...,  0.4254,  1.9157,  0.0821],
         [ 1.1693,  0.6690, -0.5932,  ..., -0.2493,  0.4333,  0.3624],
         [ 1.0068,  1.5909, -0.1440,  ..., -0.5593,  0.0276,  1.1869],
         ...,
         [ 0.0570, -0.1871, -0.6887,  ...,  1.0239,  1.0818, -0.1652],
         [-0.0700,  0.3262, -0.6664,  ...,  1.0465,  1.4056,  0.00

In [48]:
all_sentences = []
for batch in tqdm(processed_batches):
    sentences = extract_sentences_from_batch(batch)
    all_sentences.extend(sentences)  # Collect all sentences from all batches


  0%|          | 0/121 [00:00<?, ?it/s]

In [ ]:
def process_model_output(data_loader, model, device):
    model.eval()
    processed_batches = []
    with torch.no_grad():
        for data in tqdm(data_loader):
            data = {k: v.to(device) for k, v in data.items()}
            outputs = model(**data)
            batch = BatchData(
                input_ids=data['input_ids'],
                attention_mask=data['attention_mask'],
                last_hidden_states=outputs['last_hidden_state'],
                losses=outputs['losses'],
                logits=outputs['logits'],
                labels=data['labels'],
            )
            batch.detach()
            processed_batches.append(batch)
    return processed_batches


In [52]:
class ModelOutputProcessor:
    def __init__(self, data_loader, model, device):
        self.data_loader = data_loader
        self.model = model
        self.device = device

    def process_outputs(self):
        self.model.eval()
        sentences = []
        with torch.no_grad():
            for data in tqdm(self.data_loader):
                data = {k: v.to(self.device) for k, v in data.items()}
                outputs = self.model(**data)
                batch = BatchData(
                    input_ids=data['input_ids'],
                    attention_mask=data['attention_mask'],
                    last_hidden_states=outputs['last_hidden_state'],
                    losses=outputs['losses'],
                    logits=outputs['logits'],
                    labels=data['labels'],
                )
                batch.detach()
                sentences = self.extract_sentences_from_batch(batch)
                all_sentences.extend(sentences)
        return sentences

    def extract_sentences_from_batch(batch: BatchData):
        sentences = []

        loss_start_idx = 0
        unique_values, indices = torch.unique(
            batch.input_ids, return_inverse=True
        )
        active_losses = batch.losses[indices.view(-1) != 0]
        for idx in range(batch.input_ids.size(0)):  # Iterate over each sentence in the batch
            sentence_mask = batch.input_ids[idx] != 0  # Create a mask where the input_ids are not padding

            # Use the mask to filter out padding in attention_mask, last_hidden_state, logits, labels
            if sentence_mask.any():
                input_ids = batch.input_ids[idx][sentence_mask]
                attention_mask = batch.attention_mask[idx][sentence_mask]
                last_hidden_state = batch.last_hidden_states[idx][sentence_mask]
                logits = batch.logits[idx][sentence_mask]
                label = batch.labels[idx][sentence_mask]
                actual_token_count = sentence_mask.sum()  # Number of non-padding tokens
                sentence_loss = active_losses[loss_start_idx:loss_start_idx + actual_token_count]
                loss_start_idx += actual_token_count
                sentence = SentenceData(
                                input_ids=input_ids,
                                attention_mask=attention_mask,
                                last_hidden_states=last_hidden_state,
                                losses=sentence_loss,
                                logits=logits,
                                labels=label
                            )
                sentences.append(sentence)
        return sentences

In [117]:
ModelOutputProcessor()

SentenceData(input_ids=tensor([    2, 40508, 32479,    19, 33014, 34675, 43752,   466,    19,  2279,
        25896,  1089,  1098,  1161,   921,  7410, 16661,   306,  2767,  4119,
        19020, 31490,  8500, 10926, 18694,  1000, 13567,   139,  2801,  3011,
         7996,   305,  7377, 40508, 50014,   197,   305, 26258,  2050,   492,
         3812,  6700, 18112,   306,  9520,  2657, 20195,    20,     3]), attention_mask=tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1]), last_hidden_states=tensor([[ 0.4485,  0.0872, -1.0895,  ...,  0.4254,  1.9157,  0.0821],
        [ 1.1693,  0.6690, -0.5932,  ..., -0.2493,  0.4333,  0.3624],
        [ 1.0068,  1.5909, -0.1440,  ..., -0.5593,  0.0276,  1.1869],
        ...,
        [ 0.1431, -0.9956, -1.0887,  ...,  0.4026,  1.4030, -0.3296],
        [ 0.3733, -0.0979, -1.0433,  ...,  0.2927,  1.6223, -0.0199],
        [ 1.4138,  0.5

In [ ]:
sentences[0].losses

tensor([0.0000e+00, 3.0585e-01, 2.1982e-02, 1.0366e-03, 2.2747e-02, 1.3149e-02,
        0.0000e+00, 0.0000e+00, 5.3392e-04, 4.0292e-05, 1.0251e-04, 1.8690e-04,
        2.0437e-03, 4.0239e-03, 4.9590e-05, 3.5405e-05, 3.8981e-05, 2.7299e-05,
        3.9934e-05, 3.8742e-05, 6.1868e-05, 5.4358e-05, 3.1590e-05, 3.4809e-05,
        8.4277e-05, 0.0000e+00, 6.2702e-05, 3.4570e-05, 4.5060e-05, 6.2941e-05,
        5.5192e-05, 3.3616e-05, 5.4142e-04, 1.5900e-02, 2.2703e-01, 0.0000e+00,
        5.4716e-05, 1.3267e-01, 8.1702e-03, 3.2782e-05, 3.7073e-05, 3.8265e-05,
        3.6001e-05, 2.6106e-05, 1.6783e-04, 7.0212e-05, 6.6397e-05, 4.4822e-05,
        0.0000e+00])

8.0

In [10]:
batch_outputs = BatchOutputs(self.outputs, self.model)
model_outputs = ModelOutputs(batch_outputs)
results = ModelResults(outputs)

NameError: name 'self' is not defined